import { Cafe, User, Review, Friend, Activity, Message, Conversation } from './types';

export const currentUser: User = {
  id: 'user1',
  username: 'coffeelover',
  email: 'user@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=coffeelover',
  accountType: 'business',
  visibility: 'public',
  language: 'en',
  reviewCount: 42,
  friendCount: 128,
};

export const mockCafes: Cafe[] = [
  {
    id: '1',
    name: 'Artisan Brew House',
    image: 'https://images.unsplash.com/photo-1648808694138-6706c5efc80a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBjYWZlJTIwaW50ZXJpb3J8ZW58MXx8fHwxNzYzMTUxMTY0fDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.8,
    reviewCount: 342,
    distance: 0.3,
    status: 'open',
    categories: ['Coffee', 'WiFi', 'Studying'],
    priceRange: 2,
    location: {
      lat: 40.7589,
      lng: -73.9851,
      address: '123 Broadway, New York, NY 10001',
    },
    hours: [
      { day: 'Monday', open: '7:00 AM', close: '8:00 PM' },
      { day: 'Tuesday', open: '7:00 AM', close: '8:00 PM' },
      { day: 'Wednesday', open: '7:00 AM', close: '8:00 PM' },
      { day: 'Thursday', open: '7:00 AM', close: '8:00 PM' },
      { day: 'Friday', open: '7:00 AM', close: '9:00 PM' },
      { day: 'Saturday', open: '8:00 AM', close: '9:00 PM' },
      { day: 'Sunday', open: '8:00 AM', close: '7:00 PM' },
    ],
    photos: [
      'https://images.unsplash.com/photo-1648808694138-6706c5efc80a?w=600',
      'https://images.unsplash.com/photo-1609050471053-8636409f9f5b?w=600',
      'https://images.unsplash.com/photo-1596253420615-f54837f5141f?w=600',
    ],
    popularTimes: [
      { day: 'Monday', hours: [20, 30, 45, 60, 70, 85, 90, 80, 75, 60, 45, 30, 25, 20] },
      { day: 'Tuesday', hours: [25, 35, 50, 65, 75, 88, 92, 85, 78, 65, 50, 35, 28, 22] },
      { day: 'Wednesday', hours: [22, 32, 48, 63, 73, 86, 91, 83, 76, 63, 48, 33, 26, 20] },
      { day: 'Thursday', hours: [28, 38, 53, 68, 78, 90, 95, 88, 80, 68, 53, 38, 30, 25] },
      { day: 'Friday', hours: [35, 45, 60, 75, 85, 95, 98, 92, 85, 75, 60, 45, 35, 28] },
      { day: 'Saturday', hours: [40, 55, 70, 82, 90, 95, 97, 93, 87, 78, 65, 50, 38, 30] },
      { day: 'Sunday', hours: [30, 45, 60, 72, 80, 88, 90, 85, 78, 68, 55, 42, 32, 25] },
    ],
    amenities: ['WiFi', 'Outlets', 'Quiet', 'Pet Friendly', 'Outdoor Seating'],
    description: 'A modern coffee shop perfect for working and studying. Known for specialty pour-overs and exceptional espresso drinks.',
    aiAnalysis: 'Artisan Brew House excels in providing a productive workspace atmosphere with reliable WiFi and ample seating. The coffee quality is consistently high, with a focus on single-origin beans. Peak times are 8-10 AM and 2-4 PM on weekdays. Best for: remote work, studying, coffee enthusiasts.',
  },
  {
    id: '2',
    name: 'Cozy Corner Cafe',
    image: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3p5JTIwY29mZmVlJTIwc2hvcHxlbnwxfHx8fDE3NjMyMDMyMDB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.6,
    reviewCount: 218,
    distance: 0.7,
    status: 'open',
    categories: ['Coffee', 'Vibes', 'Dates', 'Pastries'],
    priceRange: 2,
    location: {
      lat: 40.7575,
      lng: -73.9845,
      address: '456 Madison Ave, New York, NY 10022',
    },
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '7:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '7:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '7:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '7:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Saturday', open: '9:00 AM', close: '8:00 PM' },
      { day: 'Sunday', open: '9:00 AM', close: '6:00 PM' },
    ],
    photos: [
      'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=600',
      'https://images.unsplash.com/photo-1648808694138-6706c5efc80a?w=600',
    ],
    popularTimes: [
      { day: 'Monday', hours: [15, 25, 40, 55, 65, 75, 80, 70, 60, 50, 40, 30, 20, 15] },
      { day: 'Tuesday', hours: [18, 28, 43, 58, 68, 78, 83, 73, 63, 53, 43, 33, 23, 18] },
      { day: 'Wednesday', hours: [16, 26, 41, 56, 66, 76, 81, 71, 61, 51, 41, 31, 21, 16] },
      { day: 'Thursday', hours: [20, 30, 45, 60, 70, 80, 85, 75, 65, 55, 45, 35, 25, 20] },
      { day: 'Friday', hours: [25, 35, 50, 65, 75, 85, 90, 80, 70, 60, 50, 40, 30, 25] },
      { day: 'Saturday', hours: [30, 40, 55, 70, 80, 88, 92, 85, 75, 65, 55, 45, 35, 30] },
      { day: 'Sunday', hours: [22, 32, 47, 62, 72, 80, 85, 78, 68, 58, 48, 38, 28, 22] },
    ],
    amenities: ['Cozy Seating', 'Great Vibes', 'Good for Dates', 'Pastries'],
    description: 'Intimate cafe with warm lighting and comfortable seating. Perfect for catching up with friends or a casual date.',
    aiAnalysis: 'Cozy Corner Cafe provides an intimate, relaxed atmosphere ideal for socializing. The ambiance features warm lighting and comfortable seating arrangements. Known for excellent pastries and traditional coffee drinks. Best for: dates, small group meetups, casual conversations.',
  },
  {
    id: '3',
    name: 'Urban Grind',
    image: 'https://images.unsplash.com/photo-1609050471053-8636409f9f5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcGVjaWFsdHklMjBjb2ZmZWV8ZW58MXx8fHwxNzYzMjQyMjE3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.7,
    reviewCount: 456,
    distance: 1.2,
    status: 'busy',
    categories: ['Coffee', 'Working', 'Groups'],
    priceRange: 3,
    location: {
      lat: 40.7614,
      lng: -73.9776,
      address: '789 Park Ave, New York, NY 10021',
    },
    hours: [
      { day: 'Monday', open: '6:30 AM', close: '9:00 PM' },
      { day: 'Tuesday', open: '6:30 AM', close: '9:00 PM' },
      { day: 'Wednesday', open: '6:30 AM', close: '9:00 PM' },
      { day: 'Thursday', open: '6:30 AM', close: '9:00 PM' },
      { day: 'Friday', open: '6:30 AM', close: '10:00 PM' },
      { day: 'Saturday', open: '7:00 AM', close: '10:00 PM' },
      { day: 'Sunday', open: '7:00 AM', close: '8:00 PM' },
    ],
    photos: [
      'https://images.unsplash.com/photo-1609050471053-8636409f9f5b?w=600',
      'https://images.unsplash.com/photo-1596253420615-f54837f5141f?w=600',
    ],
    popularTimes: [
      { day: 'Monday', hours: [30, 45, 60, 75, 85, 92, 95, 88, 80, 70, 55, 40, 30, 25] },
      { day: 'Tuesday', hours: [32, 47, 62, 77, 87, 94, 97, 90, 82, 72, 57, 42, 32, 27] },
      { day: 'Wednesday', hours: [31, 46, 61, 76, 86, 93, 96, 89, 81, 71, 56, 41, 31, 26] },
      { day: 'Thursday', hours: [35, 50, 65, 80, 90, 95, 98, 92, 85, 75, 60, 45, 35, 30] },
      { day: 'Friday', hours: [40, 55, 70, 85, 92, 97, 99, 95, 88, 78, 65, 50, 40, 35] },
      { day: 'Saturday', hours: [45, 60, 75, 88, 95, 98, 100, 96, 90, 82, 70, 55, 45, 38] },
      { day: 'Sunday', hours: [35, 50, 65, 78, 88, 93, 95, 90, 83, 73, 60, 47, 35, 30] },
    ],
    amenities: ['Fast WiFi', 'Large Tables', 'Meeting Rooms', 'Full Menu'],
    description: 'Spacious cafe with professional atmosphere. Popular among freelancers and small teams. Extensive food and beverage menu.',
    aiAnalysis: 'Urban Grind caters to professionals and groups with spacious seating, fast WiFi, and meeting room options. The extensive menu goes beyond coffee with full breakfast and lunch offerings. Can get crowded during peak hours (9 AM-12 PM). Best for: team meetings, co-working, all-day workspace.',
  },
  {
    id: '4',
    name: 'The Daily Dose',
    image: 'https://images.unsplash.com/photo-1667985805263-5531e05c3689?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYWZlJTIwd29ya3NwYWNlJTIwbGFwdG9wfGVufDF8fHx8MTc2MzI0MjIxN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.5,
    reviewCount: 189,
    distance: 1.5,
    status: 'open',
    categories: ['Coffee', 'Quiet', 'Studying'],
    priceRange: 2,
    location: {
      lat: 40.7550,
      lng: -73.9900,
      address: '321 5th Ave, New York, NY 10016',
    },
    hours: [
      { day: 'Monday', open: '7:00 AM', close: '7:00 PM' },
      { day: 'Tuesday', open: '7:00 AM', close: '7:00 PM' },
      { day: 'Wednesday', open: '7:00 AM', close: '7:00 PM' },
      { day: 'Thursday', open: '7:00 AM', close: '7:00 PM' },
      { day: 'Friday', open: '7:00 AM', close: '8:00 PM' },
      { day: 'Saturday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Sunday', open: '8:00 AM', close: '6:00 PM' },
    ],
    photos: [
      'https://images.unsplash.com/photo-1667985805263-5531e05c3689?w=600',
    ],
    popularTimes: [
      { day: 'Monday', hours: [18, 28, 42, 56, 66, 74, 78, 70, 62, 52, 42, 32, 22, 18] },
      { day: 'Tuesday', hours: [20, 30, 44, 58, 68, 76, 80, 72, 64, 54, 44, 34, 24, 20] },
      { day: 'Wednesday', hours: [19, 29, 43, 57, 67, 75, 79, 71, 63, 53, 43, 33, 23, 19] },
      { day: 'Thursday', hours: [22, 32, 46, 60, 70, 78, 82, 74, 66, 56, 46, 36, 26, 22] },
      { day: 'Friday', hours: [25, 35, 49, 63, 73, 80, 84, 76, 68, 58, 48, 38, 28, 25] },
      { day: 'Saturday', hours: [28, 38, 52, 66, 76, 82, 86, 78, 70, 60, 50, 40, 30, 28] },
      { day: 'Sunday', hours: [24, 34, 48, 62, 72, 79, 83, 75, 67, 57, 47, 37, 27, 24] },
    ],
    amenities: ['Quiet Space', 'WiFi', 'Outlets', 'Study Friendly'],
    description: 'Quiet study-friendly cafe with enforced noise policy. Great for concentration and productivity.',
    aiAnalysis: 'The Daily Dose maintains a quiet atmosphere with an enforced noise policy, making it ideal for deep work and studying. Limited seating ensures a peaceful environment. Coffee quality is good with standard offerings. Best for: individual study sessions, reading, focused work.',
  },
  {
    id: '5',
    name: 'Terrace & Grounds',
    image: 'https://images.unsplash.com/photo-1689075326462-581d7705c0ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvdXRkb29yJTIwY2FmZSUyMHRlcnJhY2V8ZW58MXx8fHwxNzYzMjI2MzA2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.9,
    reviewCount: 523,
    distance: 2.1,
    status: 'open',
    categories: ['Coffee', 'Outdoor', 'Vibes', 'Pastries'],
    priceRange: 3,
    location: {
      lat: 40.7680,
      lng: -73.9820,
      address: '555 Central Park West, New York, NY 10024',
    },
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '9:00 PM' },
      { day: 'Saturday', open: '9:00 AM', close: '9:00 PM' },
      { day: 'Sunday', open: '9:00 AM', close: '8:00 PM' },
    ],
    photos: [
      'https://images.unsplash.com/photo-1689075326462-581d7705c0ef?w=600',
      'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=600',
    ],
    popularTimes: [
      { day: 'Monday', hours: [25, 38, 52, 65, 75, 82, 85, 78, 70, 62, 50, 38, 28, 22] },
      { day: 'Tuesday', hours: [27, 40, 54, 67, 77, 84, 87, 80, 72, 64, 52, 40, 30, 24] },
      { day: 'Wednesday', hours: [26, 39, 53, 66, 76, 83, 86, 79, 71, 63, 51, 39, 29, 23] },
      { day: 'Thursday', hours: [30, 43, 57, 70, 80, 87, 90, 83, 75, 67, 55, 43, 33, 27] },
      { day: 'Friday', hours: [35, 48, 62, 75, 85, 92, 95, 88, 80, 72, 60, 48, 38, 32] },
      { day: 'Saturday', hours: [40, 53, 67, 80, 90, 95, 98, 92, 85, 77, 65, 53, 43, 37] },
      { day: 'Sunday', hours: [32, 45, 59, 72, 82, 89, 92, 85, 77, 69, 57, 45, 35, 29] },
    ],
    amenities: ['Outdoor Seating', 'Garden', 'Pet Friendly', 'Beautiful Views'],
    description: 'Stunning outdoor terrace cafe with garden seating. Perfect for beautiful weather days and special occasions.',
    aiAnalysis: 'Terrace & Grounds offers a premium outdoor experience with extensive terrace and garden seating. The location provides beautiful views and a relaxing atmosphere. Weather-dependent but consistently excellent service and high-quality beverages. Best for: outdoor dining, special occasions, weekend brunch.',
  },
  {
    id: '6',
    name: 'Velocity Espresso',
    image: 'https://images.unsplash.com/photo-1596253420615-f54837f5141f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcnRpc2FuJTIwY29mZmVlfGVufDF8fHx8MTc2MzE4NTU3OXww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.4,
    reviewCount: 267,
    distance: 0.9,
    status: 'closed',
    categories: ['Coffee', 'Quick'],
    priceRange: 2,
    location: {
      lat: 40.7595,
      lng: -73.9870,
      address: '888 Lexington Ave, New York, NY 10065',
    },
    hours: [
      { day: 'Monday', open: '6:00 AM', close: '6:00 PM' },
      { day: 'Tuesday', open: '6:00 AM', close: '6:00 PM' },
      { day: 'Wednesday', open: '6:00 AM', close: '6:00 PM' },
      { day: 'Thursday', open: '6:00 AM', close: '6:00 PM' },
      { day: 'Friday', open: '6:00 AM', close: '6:00 PM' },
      { day: 'Saturday', open: 'Closed', close: 'Closed' },
      { day: 'Sunday', open: 'Closed', close: 'Closed' },
    ],
    photos: [
      'https://images.unsplash.com/photo-1596253420615-f54837f5141f?w=600',
    ],
    popularTimes: [
      { day: 'Monday', hours: [40, 60, 75, 85, 90, 88, 75, 60, 50, 45, 30, 20] },
      { day: 'Tuesday', hours: [42, 62, 77, 87, 92, 90, 77, 62, 52, 47, 32, 22] },
      { day: 'Wednesday', hours: [41, 61, 76, 86, 91, 89, 76, 61, 51, 46, 31, 21] },
      { day: 'Thursday', hours: [45, 65, 80, 90, 95, 93, 80, 65, 55, 50, 35, 25] },
      { day: 'Friday', hours: [48, 68, 83, 93, 98, 96, 83, 68, 58, 53, 38, 28] },
      { day: 'Saturday', hours: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
      { day: 'Sunday', hours: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
    ],
    amenities: ['Quick Service', 'To-Go Focus', 'Mobile Order'],
    description: 'Fast-paced espresso bar focused on quick service and quality coffee to-go.',
    aiAnalysis: 'Velocity Espresso specializes in quick, high-quality espresso drinks for busy professionals. Limited seating with a focus on to-go orders. Mobile ordering available. Closed weekends. Best for: morning commute, quick coffee breaks, grab-and-go.',
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r1',
    userId: 'u2',
    username: 'sarahjones',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarahjones',
    cafeId: '1',
    cafeName: 'Artisan Brew House',
    rating: 5,
    text: 'Amazing coffee and perfect atmosphere for working! The WiFi is super fast and there are plenty of outlets. My go-to spot for remote work days.',
    photos: [],
    date: '2025-11-10',
    helpful: 24,
  },
  {
    id: 'r2',
    userId: 'u3',
    username: 'mikebrown',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mikebrown',
    cafeId: '1',
    cafeName: 'Artisan Brew House',
    rating: 4,
    text: 'Great coffee, but can get quite busy during peak hours. The baristas really know their stuff though!',
    photos: [],
    date: '2025-11-08',
    helpful: 15,
  },
  {
    id: 'r3',
    userId: 'u4',
    username: 'emilychen',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emilychen',
    cafeId: '2',
    cafeName: 'Cozy Corner Cafe',
    rating: 5,
    text: 'Perfect date spot! The ambiance is so warm and inviting. Had a wonderful time here with my partner.',
    photos: [],
    date: '2025-11-12',
    helpful: 31,
  },
];

export const mockFriends: Friend[] = [
  {
    id: 'f1',
    username: 'sarahjones',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarahjones',
    status: 'friends',
    mutualFriends: 12,
    reviewCount: 89,
    visibility: 'public',
    bio: 'Coffee addict & food blogger',
    location: 'Brooklyn, NY',
    favorites: ['1', '3', '5'],
    visited: ['1', '2', '3', '4', '5'],
    liked: ['1', '2', '5'],
  },
  {
    id: 'f2',
    username: 'mikebrown',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mikebrown',
    status: 'friends',
    mutualFriends: 8,
    reviewCount: 56,
    visibility: 'private',
    bio: 'Software developer, coffee enthusiast',
    location: 'Manhattan, NY',
    favorites: ['2', '4'],
    visited: ['1', '2', '4', '6'],
    liked: ['2', '4', '6'],
  },
  {
    id: 'f3',
    username: 'emilychen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emilychen',
    status: 'friends',
    mutualFriends: 15,
    reviewCount: 124,
    visibility: 'public',
    bio: 'Latte art lover | Travel enthusiast',
    location: 'Queens, NY',
    favorites: ['1', '5', '6'],
    visited: ['1', '2', '3', '5', '6'],
    liked: ['1', '3', '5'],
  },
  {
    id: 'f4',
    username: 'alexkim',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alexkim',
    status: 'pending',
    mutualFriends: 5,
    reviewCount: 34,
    visibility: 'public',
    bio: 'Photography & espresso',
    location: 'Hoboken, NJ',
    favorites: ['3'],
    visited: ['3', '4'],
    liked: ['3'],
  },
  {
    id: 'f5',
    username: 'davidlee',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=davidlee',
    status: 'request',
    mutualFriends: 7,
    reviewCount: 67,
    visibility: 'private',
    bio: 'Startup founder | Coffee runs my code',
    location: 'Jersey City, NJ',
    favorites: ['1', '2'],
    visited: ['1', '2', '3'],
    liked: ['1'],
  },
  {
    id: 'f6',
    username: 'jessicawang',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jessicawang',
    status: 'request',
    mutualFriends: 10,
    reviewCount: 45,
    visibility: 'public',
    bio: 'Designer | Seeking cozy cafes',
    location: 'Brooklyn, NY',
    favorites: ['2', '5'],
    visited: ['1', '2', '5'],
    liked: ['2', '5'],
  },
];

export const mockActivities: Activity[] = [
  {
    id: 'a1',
    userId: 'f1',
    username: 'sarahjones',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarahjones',
    type: 'review',
    cafeId: '1',
    cafeName: 'Artisan Brew House',
    cafeImage: mockCafes[0].image,
    rating: 5,
    text: 'Amazing coffee and perfect atmosphere for working!',
    timestamp: '2 hours ago',
  },
  {
    id: 'a2',
    userId: 'f2',
    username: 'mikebrown',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mikebrown',
    type: 'visit',
    cafeId: '3',
    cafeName: 'Urban Grind',
    cafeImage: mockCafes[2].image,
    timestamp: '5 hours ago',
  },
  {
    id: 'a3',
    userId: 'f3',
    username: 'emilychen',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emilychen',
    type: 'favorite',
    cafeId: '5',
    cafeName: 'Terrace & Grounds',
    cafeImage: mockCafes[4].image,
    timestamp: '1 day ago',
  },
  {
    id: 'a4',
    userId: 'f1',
    username: 'sarahjones',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarahjones',
    type: 'review',
    cafeId: '2',
    cafeName: 'Cozy Corner Cafe',
    cafeImage: mockCafes[1].image,
    rating: 4,
    text: 'Love the vibes here! Great for catching up with friends.',
    timestamp: '2 days ago',
  },
];

export const categories = [
  'Coffee',
  'Dates',
  'Groups',
  'Outdoor',
  'Pastries',
  'Quiet',
  'Studying',
  'Vibes',
  'WiFi',
  'Working',
];

export const mockMessages: Message[] = [
  {
    id: 'm1',
    senderId: 'f1',
    receiverId: 'user1',
    text: 'Hey! Have you tried the new pour-over at Artisan Brew House?',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    read: true,
  },
  {
    id: 'm2',
    senderId: 'user1',
    receiverId: 'f1',
    text: 'Not yet! Is it good?',
    timestamp: new Date(Date.now() - 1000 * 60 * 4),
    read: true,
  },
  {
    id: 'm3',
    senderId: 'f1',
    receiverId: 'user1',
    text: 'Amazing! You have to try it. Ethiopian single origin 🤤',
    timestamp: new Date(Date.now() - 1000 * 60 * 2),
    read: false,
  },
  {
    id: 'm4',
    senderId: 'f2',
    receiverId: 'user1',
    text: 'Want to grab coffee at Urban Grind later?',
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    read: true,
  },
  {
    id: 'm5',
    senderId: 'user1',
    receiverId: 'f2',
    text: 'Sure! What time works for you?',
    timestamp: new Date(Date.now() - 1000 * 60 * 55),
    read: true,
  },
  {
    id: 'm6',
    senderId: 'f3',
    receiverId: 'user1',
    text: 'Thanks for the Terrace & Grounds recommendation! The outdoor seating is incredible',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
    read: true,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv1',
    participantIds: ['user1', 'f1'],
    participant: mockFriends[0],
    lastMessage: mockMessages[2],
    unreadCount: 1,
  },
  {
    id: 'conv2',
    participantIds: ['user1', 'f2'],
    participant: mockFriends[1],
    lastMessage: mockMessages[4],
    unreadCount: 0,
  },
  {
    id: 'conv3',
    participantIds: ['user1', 'f3'],
    participant: mockFriends[2],
    lastMessage: mockMessages[5],
    unreadCount: 0,
  },
];

export const translations = {
  en: {
    appName: 'Blend',
    home: 'Home',
    explore: 'Explore',
    map: 'Map',
    social: 'Social',
    favorites: 'Favorites',
    wantToTry: 'Want to Try',
    settings: 'Settings',
    logout: 'Logout',
    heroTitle: 'Café',
    heroTitleAccent: 'Vibe',
    heroSubtitle: 'Discover cafés by what matters most - studying, dates, vibes, or just great coffee',
    searchPlaceholder: 'Search cafés...',
    exploreButton: 'Explore',
    whatLookingFor: 'What are you looking for?',
    selectCategories: 'Select one or more categories to find the perfect spot',
    quickFilters: 'Quick filters:',
    all: 'All',
    openNow: 'Open Now',
    highestRated: 'Highest Rated',
    nearest: 'Nearest',
    loading: 'Loading...',
    reviews: 'reviews',
    miles: 'mi',
    open: 'Open',
    closed: 'Closed',
    busy: 'Busy',
    viewDetails: 'View Details',
    addToFavorites: 'Add to Favorites',
    friends: 'Friends',
    friendRequests: 'Friend Requests',
    activityFeed: 'Activity Feed',
    accountSettings: 'Account Settings',
    username: 'Username',
    email: 'Email',
    accountType: 'Account Type',
    visibility: 'Profile Visibility',
    language: 'Language',
    consumer: 'Consumer',
    business: 'Business Owner',
    public: 'Public',
    private: 'Private',
    saveChanges: 'Save Changes',
    // Categories
    coffee: 'Coffee',
    dates: 'Dates',
    groups: 'Groups',
    outdoor: 'Outdoor',
    pastries: 'Pastries',
    quiet: 'Quiet',
    studying: 'Studying',
    vibes: 'Vibes',
    wifi: 'WiFi',
    working: 'Working',
    // Additional UI elements
    back: 'Back',
    myCollections: 'My Collections',
    myCollectionsDescription: 'Your saved cafés and places you want to try',
    accountSettingsDescription: 'Manage your account settings and preferences',
    preferencesDescription: 'Customize your app experience',
    notificationsDescription: 'Manage notification preferences',
    privacyDescription: 'Control your privacy settings',
    changePhoto: 'Change Photo',
    accountTab: 'Account',
    preferencesTab: 'Preferences',
    notificationsTab: 'Notifications',
    privacyTab: 'Privacy',
    friendsTab: 'Friends',
    requestsTab: 'Requests',
    activityTab: 'Activity',
    collections: 'Collections',
    profile: 'Profile',
    connectWithFriends: 'Connect with friends and see what cafés they\'re enjoying',
    achievements: 'Achievements',
    bioLabel: 'Bio',
    locationLabel: 'Location',
    bioPlaceholder: 'Tell us about yourself...',
    locationPlaceholder: 'New York City, NY',
    characters: 'characters',
    visited: 'Visited',
    // AI and Cafe Details
    aiSummary: 'AI Summary',
    whatPeopleSay: 'What People Say',
    overview: 'Overview',
    hours: 'Hours',
    popularTimes: 'Popular Times',
    positive: 'Positive',
    negative: 'Negative',
    neutral: 'Neutral',
    // Social page
    searchUsersPlaceholder: 'Search users by username...',
    searchButton: 'Search',
    searchResults: 'Search Results',
    addFriend: 'Add Friend',
    requestSent: 'Sent',
    noUsersFound: 'No users found',
    noFriendsYet: 'No friends yet',
    useSearchBarToAddFriends: 'Use the search bar above to find and add friends!',
    addFriendsToSeeActivity: 'Add friends to see their activity here',
    noRecentActivity: 'No recent activity from your friends',
  },
  es: {
    appName: 'Blend',
    home: 'Inicio',
    explore: 'Explorar',
    map: 'Mapa',
    social: 'Social',
    favorites: 'Favoritos',
    wantToTry: 'Quiero Probar',
    settings: 'Ajustes',
    logout: 'Cerrar Sesión',
    heroTitle: 'Café',
    heroTitleAccent: 'Ambiente',
    heroSubtitle: 'Descubre cafés según lo que más importa: estudiar, citas, ambiente o simplemente buen café',
    searchPlaceholder: 'Buscar cafés...',
    exploreButton: 'Explorar',
    whatLookingFor: '¿Qué estás buscando?',
    selectCategories: 'Selecciona una o más categorías para encontrar el lugar perfecto',
    quickFilters: 'Filtros rápidos:',
    all: 'Todos',
    openNow: 'Abierto Ahora',
    highestRated: 'Mejor Valorados',
    nearest: 'Más Cercanos',
    loading: 'Cargando...',
    reviews: 'reseñas',
    miles: 'mi',
    open: 'Abierto',
    closed: 'Cerrado',
    busy: 'Ocupado',
    viewDetails: 'Ver Detalles',
    addToFavorites: 'Añadir a Favoritos',
    friends: 'Amigos',
    friendRequests: 'Solicitudes de Amistad',
    activityFeed: 'Feed de Actividad',
    accountSettings: 'Configuración de Cuenta',
    username: 'Nombre de Usuario',
    email: 'Correo Electrónico',
    accountType: 'Tipo de Cuenta',
    visibility: 'Visibilidad del Perfil',
    language: 'Idioma',
    consumer: 'Consumidor',
    business: 'Propietario de Negocio',
    public: 'Público',
    private: 'Privado',
    saveChanges: 'Guardar Cambios',
    // Categories
    coffee: 'Café',
    dates: 'Citas',
    groups: 'Grupos',
    outdoor: 'Exterior',
    pastries: 'Repostería',
    quiet: 'Tranquilo',
    studying: 'Estudiar',
    vibes: 'Ambiente',
    wifi: 'WiFi',
    working: 'Trabajar',
    // Additional UI elements
    back: 'Atrás',
    myCollections: 'Mis Colecciones',
    myCollectionsDescription: 'Tus cafés guardados y lugares que quieres probar',
    accountSettingsDescription: 'Gestiona la configuración y preferencias de tu cuenta',
    preferencesDescription: 'Personaliza tu experiencia en la aplicación',
    notificationsDescription: 'Gestiona las preferencias de notificaciones',
    privacyDescription: 'Controla tu configuración de privacidad',
    changePhoto: 'Cambiar Foto',
    accountTab: 'Cuenta',
    preferencesTab: 'Preferencias',
    notificationsTab: 'Notificaciones',
    privacyTab: 'Privacidad',
    friendsTab: 'Amigos',
    requestsTab: 'Solicitudes',
    activityTab: 'Actividad',
    collections: 'Colecciones',
    profile: 'Perfil',
    connectWithFriends: 'Conéctate con amigos y ve qué cafés están disfrutando',
    achievements: 'Logros',
    bioLabel: 'Biografía',
    locationLabel: 'Ubicación',
    bioPlaceholder: 'Cuéntanos sobre ti...',
    locationPlaceholder: 'Ciudad de Nueva York, NY',
    characters: 'caracteres',
    visited: 'Visitado',
    // AI and Cafe Details
    aiSummary: 'Resumen IA',
    whatPeopleSay: 'Lo Que Dicen',
    overview: 'Resumen',
    hours: 'Horario',
    popularTimes: 'Horas Populares',
    positive: 'Positivo',
    negative: 'Negativo',
    neutral: 'Neutral',
    // Social page
    searchUsersPlaceholder: 'Buscar usuarios por nombre...',
    searchButton: 'Buscar',
    searchResults: 'Resultados',
    addFriend: 'Añadir',
    requestSent: 'Enviado',
    noUsersFound: 'No se encontraron usuarios',
    noFriendsYet: 'Aún no tienes amigos',
    useSearchBarToAddFriends: '¡Usa la barra de búsqueda para encontrar y añadir amigos!',
    addFriendsToSeeActivity: 'Añade amigos para ver su actividad aquí',
    noRecentActivity: 'No hay actividad reciente de tus amigos',
  },
  ja: {
    appName: 'Blend',
    home: 'ホーム',
    explore: '探索',
    map: 'マップ',
    social: 'ソーシャル',
    favorites: 'お気に入り',
    wantToTry: '行きたい',
    settings: '設定',
    logout: 'ログアウト',
    heroTitle: 'カフェ',
    heroTitleAccent: 'バイブ',
    heroSubtitle: '勉強、デート、雰囲気、または美味しいコーヒーなど、最も重要なことでカフェを発見',
    searchPlaceholder: 'カフェを検索...',
    exploreButton: '探索',
    whatLookingFor: '何をお探しですか？',
    selectCategories: '完璧な場所を見つけるために1つ以上のカテゴリを選択',
    quickFilters: 'クイックフィルター：',
    all: 'すべて',
    openNow: '営業中',
    highestRated: '最高評価',
    nearest: '最寄り',
    loading: '読み込み中...',
    reviews: 'レビュー',
    miles: 'マイル',
    open: '営業中',
    closed: '閉店',
    busy: '混雑',
    viewDetails: '詳細を見る',
    addToFavorites: 'お気に入りに追加',
    friends: '友達',
    friendRequests: '友達リクエスト',
    activityFeed: 'アクティビティフィード',
    accountSettings: 'アカウント設定',
    username: 'ユーザー名',
    email: 'メール',
    accountType: 'アカウントタイプ',
    visibility: 'プロフィールの公開設定',
    language: '言語',
    consumer: '消費者',
    business: 'ビジネスオーナー',
    public: '公開',
    private: '非公開',
    saveChanges: '変更を保存',
    // Categories
    coffee: 'コーヒー',
    dates: 'デート',
    groups: 'グループ',
    outdoor: '屋外',
    pastries: 'ペストリー',
    quiet: '静か',
    studying: '勉強',
    vibes: '雰囲気',
    wifi: 'WiFi',
    working: '仕事',
    // Additional UI elements
    back: '戻る',
    myCollections: 'マイコレクション',
    myCollectionsDescription: '保存したカフェと試したい場所',
    accountSettingsDescription: 'アカウント設定と環境設定を管理',
    preferencesDescription: 'アプリの体験をカスタマイズ',
    notificationsDescription: '通知設定を管理',
    privacyDescription: 'プライバシー設定を管理',
    changePhoto: '写真を変更',
    accountTab: 'アカウント',
    preferencesTab: '環境設定',
    notificationsTab: '通知',
    privacyTab: 'プライバシー',
    friendsTab: '友達',
    requestsTab: 'リクエスト',
    activityTab: 'アクティビティ',
    collections: 'コレクション',
    profile: 'プロフィール',
    connectWithFriends: '友達とつながり、楽しんでいるカフェを見る',
    achievements: '実績',
    bioLabel: '自己紹介',
    locationLabel: '場所',
    bioPlaceholder: '自己紹介を入力してください...',
    locationPlaceholder: 'ニューヨーク市、NY',
    characters: '文字',
    visited: '訪問済み',
    // AI and Cafe Details
    aiSummary: 'AI要約',
    whatPeopleSay: 'みんなの声',
    overview: '概要',
    hours: '営業時間',
    popularTimes: '混雑時間',
    positive: 'ポジティブ',
    negative: 'ネガティブ',
    neutral: '中立',
    // Social page
    searchUsersPlaceholder: 'ユーザー名で検索...',
    searchButton: '検索',
    searchResults: '検索結果',
    addFriend: '追加',
    requestSent: '送信済み',
    noUsersFound: 'ユーザーが見つかりません',
    noFriendsYet: 'まだ友達がいません',
    useSearchBarToAddFriends: '上の検索バーを使って友達を見つけて追加しましょう！',
    addFriendsToSeeActivity: '友達を追加してアクティビティを見る',
    noRecentActivity: '友達の最近のアクティビティはありません',
  },
  ko: {
    appName: 'Blend',
    home: '홈',
    explore: '탐색',
    map: '지도',
    social: '소셜',
    favorites: '즐겨찾기',
    wantToTry: '가보고 싶은',
    settings: '설정',
    logout: '로그아웃',
    heroTitle: '카페',
    heroTitleAccent: '분위기',
    heroSubtitle: '공부, 데이트, 분위기 또는 훌륭한 커피 등 가장 중요한 것으로 카페 발견',
    searchPlaceholder: '카페 검색...',
    exploreButton: '탐색',
    whatLookingFor: '무엇을 찾고 계신가요?',
    selectCategories: '완벽한 장소를 찾기 위해 하나 이상의 카테고리를 선택하세요',
    quickFilters: '빠른 필터:',
    all: '전체',
    openNow: '영업 중',
    highestRated: '최고 평점',
    nearest: '가장 가까운',
    loading: '로딩 중...',
    reviews: '리뷰',
    miles: '마일',
    open: '영업 중',
    closed: '닫힘',
    busy: '혼잡',
    viewDetails: '세부 정보 보기',
    addToFavorites: '즐겨찾기에 추가',
    friends: '친구',
    friendRequests: '친구 요청',
    activityFeed: '활동 피드',
    accountSettings: '계정 설정',
    username: '사용자 이름',
    email: '이메일',
    accountType: '계정 유형',
    visibility: '프로필 공개 설정',
    language: '언어',
    consumer: '소비자',
    business: '비즈니스 소유자',
    public: '공개',
    private: '비공개',
    saveChanges: '변경 사항 저장',
    // Categories
    coffee: '커피',
    dates: '데이트',
    groups: '그룹',
    outdoor: '야외',
    pastries: '케이크',
    quiet: '조용한',
    studying: '공부',
    vibes: '분위기',
    wifi: 'WiFi',
    working: '작업',
    // Additional UI elements
    back: '뒤로',
    myCollections: '내 컬렉션',
    myCollectionsDescription: '저장한 카페와 가보고 싶은 곳',
    accountSettingsDescription: '계정 설정 및 환경설정 관리',
    preferencesDescription: '앱 경험 맞춤 설정',
    notificationsDescription: '알림 환경설정 관리',
    privacyDescription: '개인정보 설정 관리',
    changePhoto: '사진 변경',
    accountTab: '계정',
    preferencesTab: '환경설정',
    notificationsTab: '알림',
    privacyTab: '개인정보',
    friendsTab: '친구',
    requestsTab: '요청',
    activityTab: '활동',
    collections: '컬렉션',
    profile: '프로필',
    connectWithFriends: '친구와 연결하고 그들이 즐기는 카페를 확인하세요',
    achievements: '업적',
    bioLabel: '소개',
    locationLabel: '위치',
    bioPlaceholder: '자기소개를 입력하세요...',
    locationPlaceholder: '뉴욕, NY',
    characters: '자',
    visited: '방문함',
    aiSummary: 'AI 요약',
    whatPeopleSay: '사람들의 말',
    overview: '개요',
    hours: '영업시간',
    popularTimes: '혼잡 시간',
    positive: '긍정적',
    negative: '부정적',
    neutral: '중립',
    // Social page
    searchUsersPlaceholder: '사용자 이름으로 검색...',
    searchButton: '검색',
    searchResults: '검색 결과',
    addFriend: '추가',
    requestSent: '전송됨',
    noUsersFound: '사용자를 찾을 수 없습니다',
    noFriendsYet: '아직 친구가 없습니다',
    useSearchBarToAddFriends: '위의 검색창을 사용하여 친구를 찾고 추가하세요!',
    addFriendsToSeeActivity: '친구를 추가하여 활동을 확인하세요',
    noRecentActivity: '친구의 최근 활동이 없습니다',
  },
  zh: {
    appName: 'Blend',
    home: '首页',
    explore: '探索',
    map: '地图',
    social: '社交',
    favorites: '收藏',
    wantToTry: '想去',
    settings: '设置',
    logout: '登出',
    heroTitle: '咖啡馆',
    heroTitleAccent: '氛围',
    heroSubtitle: '根据最重要的事情发现咖啡馆 - 学习、约会、氛围或只是好咖啡',
    searchPlaceholder: '搜索咖啡馆...',
    exploreButton: '探索',
    whatLookingFor: '您在寻找什么？',
    selectCategories: '选择一个或多个类别以找到完美的地点',
    quickFilters: '快速筛选：',
    all: '全部',
    openNow: '营业中',
    highestRated: '最高评分',
    nearest: '最近',
    loading: '加载中...',
    reviews: '评论',
    miles: '英里',
    open: '营业中',
    closed: '关闭',
    busy: '繁忙',
    viewDetails: '查看详情',
    addToFavorites: '添加到收藏',
    friends: '朋友',
    friendRequests: '好友请求',
    activityFeed: '活动动态',
    accountSettings: '账户设置',
    username: '用户名',
    email: '电子邮件',
    accountType: '账户类型',
    visibility: '个人资料可见性',
    language: '语言',
    consumer: '消费者',
    business: '企业主',
    public: '公开',
    private: '私密',
    saveChanges: '保存更改',
    // Categories
    coffee: '咖啡',
    dates: '约会',
    groups: '群组',
    outdoor: '户外',
    pastries: '糕点',
    quiet: '安静',
    studying: '学习',
    vibes: '氛围',
    wifi: 'WiFi',
    working: '工作',
    // Additional UI elements
    back: '返回',
    myCollections: '我的收藏',
    myCollectionsDescription: '您保存的咖啡馆和想去的地方',
    accountSettingsDescription: '管理您的帐户设置和偏好',
    preferencesDescription: '自定义您的应用体验',
    notificationsDescription: '管理通知偏好设置',
    privacyDescription: '控制您的隐私设置',
    changePhoto: '更换照片',
    accountTab: '账户',
    preferencesTab: '偏好设置',
    notificationsTab: '通知',
    privacyTab: '隐私',
    friendsTab: '好友',
    requestsTab: '请求',
    activityTab: '动态',
    collections: '收藏',
    profile: '个人资料',
    connectWithFriends: '与朋友联系，看看他们在享受哪些咖啡馆',
    achievements: '成就',
    bioLabel: '简介',
    locationLabel: '位置',
    bioPlaceholder: '介绍一下自己...',
    locationPlaceholder: '纽约, NY',
    characters: '字符',
    visited: '已访问',
    aiSummary: 'AI摘要',
    whatPeopleSay: '大家怎么说',
    overview: '概览',
    hours: '营业时间',
    popularTimes: '热门时段',
    positive: '积极',
    negative: '消极',
    neutral: '中性',
    // Social page
    searchUsersPlaceholder: '按用户名搜索...',
    searchButton: '搜索',
    searchResults: '搜索结果',
    addFriend: '添加',
    requestSent: '已发送',
    noUsersFound: '未找到用户',
    noFriendsYet: '还没有好友',
    useSearchBarToAddFriends: '使用上方搜索栏查找并添加好友！',
    addFriendsToSeeActivity: '添加好友以查看他们的动态',
    noRecentActivity: '好友没有最近的动态',
  },
};